name: Tests
on:
  push:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0']
        dependency-version: [prefer-stable]
    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.10.0
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
        env:
          APP_ENV: testing

      - name: Run tests
        run: ./vendor/bin/phpunit
